version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/circleci/android
  android: circleci/android@2.5.0

jobs:
  unittests:
    working_directory: ~/code
    docker:
      - image: cimg/android:2024.01.1
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Create secrets.properties
          command: echo -e "gfroerli_api_key_public=testing\nmapbox_access_token=testing\n" > app/secrets.properties
      - restore_cache:
          key: v1-jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

  androidtests:
    parameters:
      system-image:
        type: string
    machine:
      image: android:2024.01.1
    resource_class: large
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: << parameters.system-image >>


workflows:
  test:
    jobs:
      - unittests
      - androidtests:
          matrix:
            alias: androidtests-all
            parameters:
              system-image:
                - system-images;android-21;default;x86
                - system-images;android-34;google_apis;x86_64
          name: "androidtests:<<matrix.system-image>>"
