version: 2.

orbs:
  # https://circleci.com/developer/orbs/orb/circleci/android
  android: circleci/android@2.0.0

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: cimg/android:2022.01.1
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Create secrets.properties
          command: echo -e "gfroerli_api_key_public=testing\nmapbox_access_token=testing\n" > app/secrets.properties
      - restore_cache:
          key: v1-jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
